"""
models.py — SQLAlchemy ORM models for AI Project Pulse.

Schema:
  projects  → users (many-to-many via user.project_id for simplicity in MVP)
  updates   → belongs to user + project
  blockers  → belong to an update + project (tracked across days)
  digests   → one per project per day, generated by AI
"""

from datetime import date, datetime
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Text, Date, DateTime,
    ForeignKey, Enum, JSON,
)
from sqlalchemy.orm import relationship
import enum

from database import Base


# ── Enums ──────────────────────────────────────────────────────────────────

class UserRole(str, enum.Enum):
    employee = "employee"
    manager  = "manager"


class BlockerType(str, enum.Enum):
    waiting_on_person   = "waiting_on_person"
    waiting_on_decision = "waiting_on_decision"
    technical           = "technical"
    other               = "other"


class BlockerStatus(str, enum.Enum):
    open      = "open"
    confirmed = "confirmed"
    dismissed = "dismissed"
    resolved  = "resolved"


# ── Models ─────────────────────────────────────────────────────────────────

class Project(Base):
    __tablename__ = "projects"

    id   = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), unique=True, nullable=False)

    users    = relationship("User",    back_populates="project")
    updates  = relationship("Update",  back_populates="project")
    blockers = relationship("Blocker", back_populates="project")
    digests  = relationship("Digest",  back_populates="project")


class User(Base):
    __tablename__ = "users"

    id         = Column(Integer, primary_key=True, index=True)
    name       = Column(String(100), nullable=False)
    role       = Column(Enum(UserRole), nullable=False, default=UserRole.employee)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=True)

    project = relationship("Project", back_populates="users")
    updates = relationship("Update",  back_populates="user")


class Update(Base):
    __tablename__ = "updates"

    id         = Column(Integer, primary_key=True, index=True)
    user_id    = Column(Integer, ForeignKey("users.id"),    nullable=False)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    date       = Column(Date, nullable=False, default=date.today)
    # Combined free-text blob (Stage 2 API input)
    raw_text    = Column(Text, nullable=True)
    # Individual form fields populated by Stage 6 UI (nullable for Stage 2 compatibility)
    did        = Column(Text, nullable=True)          # "what I did"
    next_steps = Column(Text, nullable=True)          # "what's next"
    blocking   = Column(Text, nullable=True)          # "what's blocking me"
    # AI-parsed structured output stored as JSON
    parsed_json = Column(JSON, nullable=True)
    created_at  = Column(DateTime, default=datetime.utcnow)

    user     = relationship("User",    back_populates="updates")
    project  = relationship("Project", back_populates="updates")
    blockers = relationship("Blocker", back_populates="update")


class Blocker(Base):
    __tablename__ = "blockers"

    id              = Column(Integer, primary_key=True, index=True)
    update_id       = Column(Integer, ForeignKey("updates.id"),   nullable=False)
    project_id      = Column(Integer, ForeignKey("projects.id"),  nullable=False)
    type            = Column(Enum(BlockerType), nullable=False, default=BlockerType.other)
    description     = Column(Text, nullable=False)
    first_seen_date = Column(Date, nullable=False, default=date.today)
    last_seen_date  = Column(Date, nullable=False, default=date.today)
    days_recurring  = Column(Integer, nullable=False, default=1)
    status          = Column(Enum(BlockerStatus), nullable=False, default=BlockerStatus.open)
    created_at      = Column(DateTime, default=datetime.utcnow)
    updated_at      = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    update  = relationship("Update",  back_populates="blockers")
    project = relationship("Project", back_populates="blockers")


class Digest(Base):
    __tablename__ = "digests"

    id               = Column(Integer, primary_key=True, index=True)
    project_id       = Column(Integer, ForeignKey("projects.id"), nullable=False)
    date             = Column(Date, nullable=False, default=date.today)
    summary_text     = Column(Text, nullable=False)
    # List of blocker IDs included in this digest as flagged risks
    flagged_blockers = Column(JSON, nullable=True, default=list)
    created_at       = Column(DateTime, default=datetime.utcnow)

    project = relationship("Project", back_populates="digests")
